### ISSUE TITLE
The first Snackbar will not automatically dismiss itself

### ISSUE THREAD

**Issue by ProfessionalRBX** [RoStrap/RoStrapUI#34]
Users with Snackbar should have the ability to do `Snackbar:Dismiss()` in order to have the ability to make the Snackbar automatically disappear after a certain amount of time even without the action button being pressed.

**Comment by Validark** [comment]
Snackbars already should automatically disappear after a certain amount of time. Are they not doing so for you?

**Comment by Thundermaker300** [comment]
What happens is they don't disappear if a snackbar has not occurred previously (the first snackbar to occur for the player doesn't go away automatically).  All other snackbars after the first work.

**Comment by Validark** [comment]
Could someone send me a place file with this problem? I can't reproduce it.

**Comment by Validark** [comment]
Does this work now?
