### ISSUE TITLE
Ripple Button hover effect fails to disappear when no longer hovering

### ISSUE THREAD

**Issue by YukiSuter** [RoStrap/RoStrapUI#37]
![image](https://user-images.githubusercontent.com/16707981/57183931-8f0d7e80-6eab-11e9-81ac-2e0ef68cbb8f.png)

The ripple button hover effect will not disappear once the mouse has left the button.

**Comment by Validark** [comment]
Works fine for me. Can you provide a reproduction of the issue you are having? Like a place file?

**Comment by Validark** [comment]
Make sure your ZIndexBehavior is set to Global!
